// ts2fable 0.0.0
module rec globalClass
open System
open Fable.Core
open Fable.Core.JS


type [<AllowNullLiteral>] IExports =
    abstract AutoGeneratedKeyType: AutoGeneratedKeyTypeStatic

type [<AllowNullLiteral>] AutoGeneratedKeyType =
    interface end

type [<AllowNullLiteral>] AutoGeneratedKeyTypeStatic =
    [<Emit "new $0($1...)">] abstract Create: unit -> AutoGeneratedKeyType
    abstract Identity: AutoGeneratedKeyType with get, set
    abstract KeyGenerator: AutoGeneratedKeyType with get, set
    abstract None: AutoGeneratedKeyType with get, set
